In [55]:
import pandas as pd 
import numpy as np 
from sqlalchemy import create_engine

In [56]:
engine = create_engine("postgresql://postgres:0000@localhost:5432/olist_db")

In [57]:
df_orders = pd.read_sql("SELECT * FROM order_summary", engine)
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_payment,payment_count,avg_payment,total_items,total_product_value,total_freight_value,avg_review_score,total_reviews,delivery_time_days,estimated_delivery_days,delivery_delay_days
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,72.19,1,72.19,1,58.90,13.29,5.0,1,7.614421,15.625671,-8.011250
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,259.83,1,259.83,1,239.90,19.93,4.0,1,16.216181,18.546458,-2.330278
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,216.87,1,216.87,1,199.00,17.87,5.0,1,7.948437,21.393391,-13.444954
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,25.78,1,25.78,1,12.99,12.79,4.0,1,6.147269,11.582928,-5.435660
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,218.04,1,218.04,1,199.90,18.14,5.0,1,25.114352,40.418160,-15.303808

In [58]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   total_payment                  99441 non-null  float64
 9   payment_count                  99441 non-null  int64
 10  avg_payment                    99441 non-null  float64
 11  total_items                    99441 non-null  int64
 12  total_product_value            99441 non-null  float64
 13  total_freight_value            99441 non-null  float64
 14  avg_review_score               99441 non-null  float64
 15  total_reviews                  99441 non-null  int64
 16  delivery_time_days             96476 non-null  float64
 17  estimated_delivery_days        99441 non-null  float64
 18  delivery_delay_days            96476 non-null  float64
dtypes: datetime64[ns](5), float64(8), int64(3), object(3)
memory usage: 14.4+ MB

In [59]:
df_orders = df_orders.drop_duplicates()

In [60]:
df_orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
total_payment                       0
payment_count                       0
avg_payment                         0
total_items                         0
total_product_value                 0
total_freight_value                 0
avg_review_score                    0
total_reviews                       0
delivery_time_days               2965
estimated_delivery_days             0
delivery_delay_days              2965
dtype: int64

In [61]:
# Removing Orders with Invalid Date Sequences
invalid_orders = df_orders[
    (
        (df_orders['order_approved_at'].notna()) &
        (df_orders['order_delivered_customer_date'].notna()) &
        (df_orders['order_approved_at'] > df_orders['order_delivered_customer_date'])
    )
    |
    (
        (df_orders['order_approved_at'].notna()) &
        (df_orders['order_delivered_carrier_date'].notna()) &
        (df_orders['order_approved_at'] > df_orders['order_delivered_carrier_date'])
    )
]

df_orders.drop(invalid_orders.index , inplace=True)

In [62]:
# Checking purchase vs approval

df_orders[df_orders['order_purchase_timestamp'] > df_orders['order_approved_at']]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, total_payment, payment_count, avg_payment, total_items, total_product_value, total_freight_value, avg_review_score, total_reviews, delivery_time_days, estimated_delivery_days, delivery_delay_days]
Index: []

In [63]:
# checking delivery vs purchase 
df_orders[df_orders['order_delivered_customer_date'] < df_orders['order_purchase_timestamp']]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, total_payment, payment_count, avg_payment, total_items, total_product_value, total_freight_value, avg_review_score, total_reviews, delivery_time_days, estimated_delivery_days, delivery_delay_days]
Index: []

In [64]:
# checking purchase vs delivered customer date
df_orders[df_orders['order_purchase_timestamp'] > df_orders['order_delivered_customer_date']]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, total_payment, payment_count, avg_payment, total_items, total_product_value, total_freight_value, avg_review_score, total_reviews, delivery_time_days, estimated_delivery_days, delivery_delay_days]
Index: []

In [65]:
# Checking negative delivery time
df_orders[df_orders['delivery_time_days'] < 0 ]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, total_payment, payment_count, avg_payment, total_items, total_product_value, total_freight_value, avg_review_score, total_reviews, delivery_time_days, estimated_delivery_days, delivery_delay_days]
Index: []

In [79]:
# Checking zero or negative Payment
df_orders[df_orders['total_payment']<= 0] #order status is canceled ,  makes sense

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_payment,payment_count,avg_payment,total_items,total_product_value,total_freight_value,avg_review_score,total_reviews,delivery_time_days,estimated_delivery_days,delivery_delay_days
251,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12,0.0,1,0.0,0,0.0,0.0,1.0,1,NaN,14.356493,NaN
27282,4637ca194b6387e2d538dc89b124b0ee,a73c1f73f5772cf801434bf984b0b1a7,canceled,2018-09-03 14:14:25,NaT,NaT,NaT,2018-09-10,0.0,1,0.0,0,0.0,0.0,3.0,1,NaN,6.406655,NaN
78008,c8c528189310eaa44a745b8d9d26908b,197a2a6a77da93f678ea0d379f21da0a,canceled,2018-08-28 20:05:14,NaT,NaT,NaT,2018-09-11,0.0,1,0.0,0,0.0,0.0,1.0,1,NaN,13.163032,NaN

In [75]:
df_orders[df_orders['total_payment'] < df_orders['total_product_value']][['total_payment','total_product_value' ]]

# In some cases, total_payment is slightly lower than total_product_value.
# The differences are generally small, suggesting possible discounts,
# rounding effects, or aggregation inconsistencies.
# No major anomalies detected.

       total_payment  total_product_value
98375         212.82               217.99

In [69]:
# Orders with zero items
df_orders[(df_orders['order_status']=='delivered') & (df_orders['total_items'] <= 0)  ]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, total_payment, payment_count, avg_payment, total_items, total_product_value, total_freight_value, avg_review_score, total_reviews, delivery_time_days, estimated_delivery_days, delivery_delay_days]
Index: []

In [71]:
# Items but no payment
df_orders.drop((df_orders[(df_orders['total_items'] > 0) &(df_orders['total_payment'] == 0)]).index  , inplace = True) # only one order

In [81]:
# Delay consistency
df_orders[
    (df_orders['delivery_delay_days'] > 0) &
    (df_orders['order_delivered_customer_date'] <= df_orders['order_estimated_delivery_date'])
]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, total_payment, payment_count, avg_payment, total_items, total_product_value, total_freight_value, avg_review_score, total_reviews, delivery_time_days, estimated_delivery_days, delivery_delay_days]
Index: []

In [ ]:
# Non-delivered orders with delivery date
mask = (df_orders['order_status'] != 'delivered') & (df_orders['order_delivered_customer_date'].notna())
# Update only those rows to 'delivered'
df_orders.loc[mask, 'order_status'] = 'delivered'

In [89]:
(df_orders[(df_orders['order_status'] != 'delivered') &(df_orders['order_delivered_customer_date'].notna())])

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, total_payment, payment_count, avg_payment, total_items, total_product_value, total_freight_value, avg_review_score, total_reviews, delivery_time_days, estimated_delivery_days, delivery_delay_days]
Index: []

In [92]:
# Flag delivered orders missing delivery date

df_orders[(df_orders['order_status'] == 'delivered') & (df_orders['order_delivered_customer_date'].isna())] #8 rows 

df_orders = df_orders.drop((df_orders[(df_orders['order_status'] == 'delivered') & (df_orders['order_delivered_customer_date'].isna())]).index)

In [100]:
df_orders = df_orders[df_orders['order_approved_at'].notna()]

In [ ]:
# Keeping only delivered orders
df_orders = df_orders[df_orders['order_status'] == 'delivered']

In [105]:
df_orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     1
order_delivered_customer_date    0
order_estimated_delivery_date    0
total_payment                    0
payment_count                    0
avg_payment                      0
total_items                      0
total_product_value              0
total_freight_value              0
avg_review_score                 0
total_reviews                    0
delivery_time_days               0
estimated_delivery_days          0
delivery_delay_days              0
dtype: int64

In [106]:
df_orders = df_orders.dropna()

In [108]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95110 entries, 0 to 99440
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       95110 non-null  object
 1   customer_id                    95110 non-null  object
 2   order_status                   95110 non-null  object
 3   order_purchase_timestamp       95110 non-null  datetime64[ns]
 4   order_approved_at              95110 non-null  datetime64[ns]
 5   order_delivered_carrier_date   95110 non-null  datetime64[ns]
 6   order_delivered_customer_date  95110 non-null  datetime64[ns]
 7   order_estimated_delivery_date  95110 non-null  datetime64[ns]
 8   total_payment                  95110 non-null  float64
 9   payment_count                  95110 non-null  int64
 10  avg_payment                    95110 non-null  float64
 11  total_items                    95110 non-null  int64
 12  total_product_value            95110 non-null  float64
 13  total_freight_value            95110 non-null  float64
 14  avg_review_score               95110 non-null  float64
 15  total_reviews                  95110 non-null  int64
 16  delivery_time_days             95110 non-null  float64
 17  estimated_delivery_days        95110 non-null  float64
 18  delivery_delay_days            95110 non-null  float64
dtypes: datetime64[ns](5), float64(8), int64(3), object(3)
memory usage: 14.5+ MB